name: Terraform CI/CD

on:
  push:
    branches:
      - '**'      # Run on every branch
    paths:
      - '**.tf'   # Run only when Terraform files change

  pull_request:
    branches:
      - main      # PR targeting main will show plan

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

  Authentication:
    # AWS Credentials from GitHub Secrets
      name: Configure AWS Credentials
      runs-on: ubuntu-latest
      needs: terraform
      permissions:
        id-token: write
        contents: read
  
      steps:

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: OIDC Auth
          uses: aws-actions/configure-aws-credentials@v2
          with:
            #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
            aws-region: ap-south-1
            #role-skip-session-tagging: trues

      # Initialize Terraform
        - name: Terraform Init
          run: terraform init -input=false
  
        # Validate the configuration
        - name: Terraform Validate
          run: terraform validate
  
        # ---- Terraform Plan on commit OR PR ----
        - name: Terraform Plan
          if: github.event_name == 'push' || github.event_name == 'pull_request'
          run: terraform plan -input=false
  
        # ---- Terraform Apply ONLY after PR merged into main ----
        - name: Terraform Apply
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          run: terraform apply -auto-approve -input=false

