name: Terraform CI/CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - 'main'
    paths:
      - "**/**.tf"
  pull_request:
    branches:
      - main
    paths:
      - "**/**.tf"
      
  workflow_dispatch:

jobs:

  # -----------------------------
  # 1. Checkout code + Setup Terraform
  # -----------------------------
  # setup:
  #   name: Setup Environment
  #   runs-on: ubuntu-latest

  #   outputs:
  #     terraform_version: 1.6.0

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       id: tf
  #       with:
  #         terraform_version: 1.6.0

  # -----------------------------
  # 2. AWS Authentication via OIDC
  # -----------------------------
  # auth:
  #   name: AWS OIDC Authentication
  #   runs-on: ubuntu-latest
  #   needs: setup

  #   steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Configure AWS Credentials (OIDC)
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
      #     aws-region: ap-south-1

  # -----------------------------
  # 3. Terraform Init + Validate
  # -----------------------------
  init_setup:
    name: Initial Setup
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository # download gitrepo to vm
        uses: actions/checkout@v3
     
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
          aws-region: ap-south-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # 
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: .
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: .
        run: terraform validate

  # -----------------------------
  # 4. Terraform Plan
  # -----------------------------
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: init_validate

    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: .
        run: terraform init -input=false
      
      - name: Terraform Plan
        working-directory: .
        run: terraform plan -input=false

  # -----------------------------
  # 5. Terraform Apply (Only on main)
  # -----------------------------
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan

    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
          aws-region: ap-south-1
      - name: Terraform Init
        working-directory: .
        run: terraform init -input=false
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
  # -----------------------------
  # 5. Terraform destroy (Only on main)
  # -----------------------------
  destroy:
     name: Terraform Destroy (Manual)
     runs-on: ubuntu-latest
     needs: apply

     if: github.event_name == 'workflow_dispatch'

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.6.0

       - name: Configure AWS Credentials (OIDC)
         uses: aws-actions/configure-aws-credentials@v2
         with:
           role-to-assume: arn:aws:iam::156916773321:role/OIDC-connection
           aws-region: ap-south-1

       - name: Terraform Init
         working-directory: .
         run: terraform init -input=false

       - name: Terraform Destroy
         run: terraform destroy -auto-approve -input=false

